#!/bin/bash

DOCKER_HUB_PROJECT="192.168.2.253:5000/rnd-dev"
TAG_NAME="develop:2021-06-29"
LATEST_TAG_NAME="develop:latest"

docker tag ${TAG_NAME} ${DOCKER_HUB_PROJECT}/${TAG_NAME}
docker push ${DOCKER_HUB_PROJECT}/${TAG_NAME}

docker tag ${TAG_NAME} ${DOCKER_HUB_PROJECT}/${LATEST_TAG_NAME}
docker push ${DOCKER_HUB_PROJECT}/${LATEST_TAG_NAME}
