#!/bin/bash

DOCKER_HUB_PROJECT="192.168.2.253:5000/development"
IMAGE_NAME="centos-systemd"
IMAGE_TAG="7"

IMAGE_TAG_LATEST="latest"

docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${DOCKER_HUB_PROJECT}/${IMAGE_NAME}:${IMAGE_TAG}
docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${DOCKER_HUB_PROJECT}/${IMAGE_NAME}:${IMAGE_TAG_LATEST}

docker push ${DOCKER_HUB_PROJECT}/${IMAGE_NAME}:${IMAGE_TAG}
docker push ${DOCKER_HUB_PROJECT}/${IMAGE_NAME}:${IMAGE_TAG_LATEST}
